spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        cache:
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_second_level_cache: true
        javax.cache:
          uri: classpath:cache.xml
          provider: org.ehcache.jsr107.EhcacheCachingProvider
        session_factory.statement_inspector: com.mickaelb.integration.hibernate.HibernateStatementInspector
logging:
  level:
    org.hibernate: info

