spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        session_factory.statement_inspector: com.mickaelb.integration.hibernate.HibernateStatementCountInspector
logging:
  level:
    org.hibernate: info
